ucontext.h: Add __INDIRECT_RETURN
On x86, swapcontext may return via indirect branch when shadow stack is
enabled.  Add __INDIRECT_RETURN to swapcontext to mark it return via
indirect branch.

A patch has been sent to GCC to add indirect_return attribute.  In the
meantime, __INDIRECT_RETURN is defined with returns_twice attribute.
We need to define it as empty in string/tst-xbzero-opt.c to avoid:

tst-xbzero-opt.c: In function ‘prepare_test_buffer’:
tst-xbzero-opt.c:105:1: error: function ‘prepare_test_buffer’ can never be inlined because it uses setjmp
 prepare_test_buffer (unsigned char *buf)

	* stdlib/ucontext.h (__INDIRECT_RETURN): New.  Define if not
	defined.
	(swapcontext): Add __INDIRECT_RETURN.
	* string/tst-xbzero-opt.c (__INDIRECT_RETURN): New.
	* sysdeps/unix/sysv/linux/x86/sys/ucontext.h
	(__INDIRECT_RETURN): Defined if shadow stack is enabled.